root: true
env:
  browser: true
  es6: true
  jquery: true
extends: 'airbnb'
globals: 
  Drupal: true
  drupalSettings: true
  drupalTranslations: true
  domready: true
  jQuery: true
  matchMedia: true
  Modernizr: true
  CKEDITOR: true
rules:
  arrow-parens:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  curly : 
    - error
    - all
  comma-dangle: 
    - off
    - always
  comma-spacing:
    - off
  func-names :
    - error
    - never
  max-len: 
    - 1
    - 180
    - 4
  no-underscore-dangle: 
    - error
  no-unused-expressions: 0
  no-unused-vars: 
    - error
  quotes:
    - error
    - single
  semi:
    - off
    - always
  wrap-iife:
    - off
