#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'stylish'
  formatter: stylish
  # Raise an error if more than 150 warnings are generated
  max-warnings: 150
# File Options
files:
  include: 
    - 'src/components/**/*.s+(a|c)ss'
    - 'src/regions/**/*.s+(a|c)ss'
  ignore:
    - 'src/vendor/**/*.*'
# Rule Configuration
rules:
  #extends-before-mixins: 1
  #extends-before-declarations: 1
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 0

  no-warn: 0
  no-debug: 1
  no-ids: 0
  no-important: 0
  hex-notation:
    - 0
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  #property-sort-order:
  #  - 1
  #  -
  #    order:
  #      - display
  #      - margin
  #    ignore-custom-properties: true
  variable-for-property: 0