id: link_title_label
label: 'Link title label'
ui_limit: ''
properties:
  content:
    value: '[block_content:field_featured_content:title]'
    format: teaser_display_text
type: token
type_label: 'Token field'
entities:
  block_content: block_content
