ignore:
  - core.date_format.long
  - core.date_format.medium
  - core.date_format.short
  - block.block.basesiteinuse.yml
  - core.extension.yml
  - devel.*
  - system.menu.devel.yml
  - webform.webform.example_*

