ignore:
  - block.block.siteinuse.yml
  - core.date_format.fallback.yml
  - core.date_format.html_*
  - core.date_format.long
  - core.date_format.medium
  - core.date_format.short
  - block.block.basesiteinuse.yml
  - core.extension.yml
  - devel.*
  - system.menu.devel.yml
  - webform.webform.example_*
  - webform.webform_options.*
  - webform.webform.contact.yml
  - block.block.bartik*
  - block.block.bootstrap_*
  - system.action.*
  - image.style.linkit_result_thumbnail.yml
  - media.settings.yml
  - embed.button.*
  - linkit.linkit_profile.default.yml

