<?php

use Drupal\user\Entity\User;
use Drupal\Core\Entity\EntityPublishedInterface;

/**
 * @file
 */

/**
 * Implements hook_page_attachments().
 *
 * Loads the CSS for the admin theme.
 */
function sector_utils_page_attachments(array &$attachments) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  // Lets just keep this for the default admin theme. If people have changed
  // they probably have their own styles/look.
  if ($theme == 'seven') {
    $attachments['#attached']['library'][] = 'sector_utils/admin';
  }
}



/**
 * Implements hook_form_alter().
 *
 * Improve page node status checkbox by changing the label
 * from "Publishing status" to "Publish" and removing the description.
 *
 * This should bring it in line with all other content types.
 */
function sector_utils_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'node_page_form':
    case 'node_page_edit_form':
      $element = &$form['status']['widget']['value'];
      $element['#title'] = t('Published');
      $element['#description'] = t('');
      break;
  }
}

/**
 * Implements hook_contextual_links_view_alter().
 *
 * Hides the configure block link based if the user doesn't have the right
 * permission.
 */
function sector_utils_contextual_links_view_alter(&$element, $items) {
  $user = \Drupal::currentUser();

  if(isset($element['#links']['block-configure'])) {
    if (!$user->hasPermission('configure blocks from contextual links')) {
      unset($element['#links']['block-configure']);
    }
  }
}

/**
 * Implements hook_ds_pre_render_alter().
 *
 * Add entity-status-unpublished class to all view modes other than full.
 * CSS in the theme will add a visual indicator to allow editors to recognise
 * unpublished content.
 */
function sector_utils_ds_pre_render_alter(array &$layout_render_array, array $context, array &$vars) {
  if ($layout_render_array['#view_mode'] != 'full'
    && !empty($context['entity'])
    && $context['entity'] instanceof EntityPublishedInterface
    && !$context['entity']->isPublished()){
    $vars['attributes']['class'][] = 'entity-status-unpublished';
  }
}
