<?php

function sector_toc_uninstall() {

    // delete block
    $block = \Drupal::service('entity.repository')->loadEntityByUuid('block', '6930bbb6-7bd5-45d3-8689-f9b8bbbe2fa9');
    if($block) {
        $block->delete();
    }

    // delete taxonomy term
    $term = \Drupal::service('entity.repository')->loadEntityByUuid('taxonomy_term', '382a97ea-f873-46e7-b827-e9603edb5a17');
    if($term) {
        $term->delete();
    }
}