_meta:
  version: '1.0'
  entity_type: taxonomy_term
  uuid: ce6a9fe6-0d6b-4ea4-afe8-7d505a7fe57b
  bundle: sector_content_settings
  default_langcode: en
default:
  status:
    -
      value: true
  name:
    -
      value: 'Hide sidebar'
  weight:
    -
      value: 0
  parent:
    -
      target_id: 0
  revision_translation_affected:
    -
      value: true
  path:
    -
      alias: ''
      langcode: en
      pathauto: 0