_meta:
  version: '1.0'
  entity_type: taxonomy_term
  uuid: a2c525ae-fb40-42ba-991f-d358a6152f8d
  bundle: sector_content_settings
  default_langcode: en
default:
  status:
    -
      value: true
  name:
    -
      value: 'Omit from search results'
  weight:
    -
      value: 0
  parent:
    -
      target_id: 0
  revision_translation_affected:
    -
      value: true
  path:
    -
      alias: ''
      langcode: en
      pathauto: 1