_meta:
  version: '1.0'
  entity_type: taxonomy_term
  uuid: 0505a7d0-1283-4435-9aae-06e6c9f0005e
  bundle: sector_content_settings
  default_langcode: en
default:
  status:
    -
      value: true
  name:
    -
      value: 'Show children card set'
  weight:
    -
      value: 0
  parent:
    -
      target_id: 0
  revision_translation_affected:
    -
      value: true
  path:
    -
      alias: ''
      langcode: en
      pathauto: 0