_meta:
  version: '1.0'
  entity_type: taxonomy_term
  uuid: cb1a21ce-f835-4682-b027-34f80c86c4e8
  bundle: sector_content_settings
  default_langcode: en
default:
  status:
    -
      value: true
  name:
    -
      value: 'Show last updated'
  weight:
    -
      value: 1
  parent:
    -
      target_id: 0
  revision_translation_affected:
    -
      value: true
  path:
    -
      alias: ''
      langcode: en
      pathauto: 1