id: media_copyright_link
label: 'Media copyright link'
ui_limit: ''
properties:
  content:
    value: '[media:field_copyright_license:entity:field_copyright_link:title]'
    format: plain_text
type: token
type_label: 'Token field'
entities:
  media: media
