_meta:
  version: '1.0'
  entity_type: taxonomy_term
  uuid: 382a97ea-f873-46e7-b827-e9603edb5a17
  bundle: sector_content_settings
  default_langcode: en
default:
  status:
    -
      value: true
  name:
    -
      value: 'Show table of contents'
  weight:
    -
      value: 0
  parent:
    -
      target_id: 0
  revision_translation_affected:
    -
      value: true
  path:
    -
      alias: ''
      langcode: en
      pathauto: 1