timeout: 43200
max_timeout: 43200
padding: 300
role_logout: true
redirect_url: /user/login
no_dialog: false
message: 'Your session is about to expire. Do you want to reset it?'
inactivity_message: 'You have been logged out due to inactivity.'
enforce_admin: true
jstimer_format: '%hours%:%mins%:%secs%'
jstimer_js_load_option: false
use_alt_logout_method: false
use_watchdog: true
_core:
  default_config_hash: wFltkxiyivT2p8RylUWkfexK0LhEdTyKntIO1JyH98s
