module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  admin_ui_toggle: 0
  autologout: 0
  automated_cron: 0
  better_normalizers: 0
  block: 0
  block_class: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  config_update: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  default_content: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entityqueue: 0
  field: 0
  field_formatter_filter: 0
  field_group: 0
  field_group_link: 0
  field_ui: 0
  fieldblock: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  linkit: 0
  media_entity: 0
  media_entity_document: 0
  media_entity_image: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  mmenu: 0
  node: 0
  options: 0
  page_cache: 0
  password_policy: 0
  password_policy_character_types: 0
  password_policy_history: 0
  password_policy_length: 0
  path: 0
  responsive_image: 0
  search: 0
  sector_blocks: 0
  sector_default_content: 0
  sector_wysiwyg_utils: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  term_condition: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  better_formats: 100
  sector: 1000
theme:
  bootstrap: 0
  stable: 0
  sector_starter: 0
  classy: 0
  bartik: 0
  seven: 0
profile: sector
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
