id: media_size
label: 'Media size'
ui_limit: ''
properties:
  content:
    value: "[media:field_document:entity:size]\r\n[media:image:entity:size]"
    format: teaser_display_text
type: token
type_label: 'Token field'
entities:
  media: media
_core:
  default_config_hash: y_XyrZ8UdpYE-VO4Flq_rpGYUJ-4P1rPXHG2lg2owqk
