name: 'Sector starterkit'
mail: daniel@sparksinteractive.co.nz
slogan: ''
page:
  403: /node/14
  404: /node/5
  front: /node/10
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
mail_notification: ''
_core:
  default_config_hash: v0uT4_MextCpWSf0hwJBhbKWaApN-7yyje75dT8LlV0
uuid: 55316c0b-42a8-4ce3-9c9d-2509d42a0897
